"use client";

import { Footer } from "./Components/Footer";
import { Header } from "./Components/Header";
import "../../public/css/globals.css";
import { Provider } from "react-redux";
import { store } from "./ReduxToolkit/ReduxStore";

// export const metadata = {
//   title: "Ajay Kumar (Portfolio)",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <div className="flex gap-3 md:flex-col">
            <div className="fixed inset-y-0 left-0 top-0 bg-[#54B689] h-[100vh] w-[18%] z-20 overflow-y-scroll">
              <Header />
            </div>
            <div className="basis-[80%] ms-[20%]">
              <main>{children}</main>
              <Footer />
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
