import "../../public/css/globals.css";
import { Footer } from "./Components/Footer";
import { Header } from "./Components/Header";
import { Sidebar } from "./Components/Sidebar";

export const metadata = {
  title: "Ajay Kumar (Portfolio)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-3">
          <div className="fixed start-0 bottom-0 bg-white h-full w-[20%] z-20">
            <Sidebar />
          </div>
          <div className="basis-[80%] ms-[20%]">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
